[Convert]
# true = do synchronizing, false = no sync anyway
Synchronize=True
# true/false if checking for Session- and Program-Technology, different Techs will abort Sync
TechnoCheck=True
# Logging Stage : 0=None  1=LogWindow[True,Log]  2=File  3=Both(LogWindow&File)
Logging=None
# true/false if Check File with all synchonize Items should be written
Checking=False
# true/false if the Attribute "SynchronizedProgramFrom" should be created
SyncAttrib=False

[IgnoreItems]
IgnoreItem1=GroupCycleTimeEvaluated
IgnoreItem2=OperationCycleTimeEvaluated
IgnoreItem3=LinkOperationCycleTimeEvaluated
IgnoreItem4=UploadValidViaPointOrientation
IgnoreItem5=UseRegshape
IgnoreItem6=ContourType
IgnoreItem7=GrabOffsetX
IgnoreItem8=GrabOffsetY
IgnoreItem9=GrabOffsetZ
IgnoreItem10=ReleaseOffsetX
IgnoreItem11=ReleaseOffsetY
IgnoreItem12=ReleaseOffsetZ
IgnoreItem13=UsedCollisionCheckTolerance
IgnoreItem14=PythonScriptTechnologyVersion
